name: main
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0-dev+1

environment:
  sdk: '>=3.0.0-218.1.beta'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  data:
    path: ../data
  window_manager: ^0.3.1
  system_tray: ^2.0.2
  go_router: ^6.5.2
  provider: ^6.0.5
  json_annotation: ^4.8.0
  objectbox_flutter_libs: ^2.0.0
  path_provider: ^2.0.14
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
