name: server
description: A sample command-line application.
version: 1.0.0-dev
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0-218.1.beta'

dependencies:
  alfred: ^1.1.0+1
  dart_jsonwebtoken: ^2.7.1
  data:
    path: ../data
  isolate: ^2.1.1
  json_annotation: ^4.8.0

dev_dependencies:
  i18n: ^4.0.2
  build_runner: ^2.3.3
  lints: ^2.0.0
  test: ^1.21.0
